plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.23.0",
)

plugin_repo(
    name = "shell",
    owner = "please-build",
    revision = "v0.2.0",
)
